### PR TITLE
feat: add missing fold operators

### PR DESCRIPTION
**Pull request by amaanq**
Gotta love C++, this is valid:

```cpp
#include <stdio.h>

int main() {
  int x = 1;
  int bitand y = x;
  printf("x: %d, y: %p\n", x, bitand y);
}
```

### CODE REVIEW

**Comment by jdrouhard** [comment]
Valid, but virtually never used in practice for reference identifiers.

I don't mind adding the missing fold operators since those are actual binary operators, but for the sake of keeping the parser state count lower and the size of the parser smaller, I'm inclined to not add 'bitand' to the grammar everywhere an ampersand might be valid.

**Comment by amaanq** [comment]
State counts increased by 12/6, if that's a concern (and rightfully so if sizable, it's over 6k), I'd say there are better angles to consider reducing it than this. I think this is fine as, while uncommon, I'm sure some people use it as a placeholder for &.

**Comment by jdrouhard** [comment]
> State counts increased by 12/6, if that's a concern (and rightfully so if sizable, it's over 6k), I'd say there are better angles to consider reducing it than this. I think this is fine as, while uncommon, I'm sure some people use it as a placeholder for &. 
> 
> 

For logical/bitwise binary operations, sure, but I think the usage of bitand as a reference type modifier are probably very very small (if used at all). C++ already had one of the slowest parsers out there and the actual applicability of this is vanishingly small.

I'm still leaning toward only adding the keyword for fold operators for now.

**Comment by Wdestroier** [comment]
I agree the state count increase is minimal.

**Comment by amaanq** [comment]
ping @jdrouhard

**Comment by jdrouhard** [comment]
> > I'm still leaning toward only adding the keyword for fold operators for now.
> 
> 
> 
> Oh well, done.

Did you push this change?

**Comment by amaanq** [comment]
I had thought I'd done so already, but I hadn't, done now

**Pull request merged**
