### PR TITLE
Namespace names for definition can be scoped and contain inline keyword

### PR DESCRIPTION
**Pull request by calixteman**
For reference:
https://en.cppreference.com/w/cpp/language/namespace

### CODE REVIEW

**Comment by jdrouhard** [comment]
@maxbrunsfeld can we get this one merged? I came here to start working on this very change and saw @calixteman implemented it over a year ago :)

**Comment by jdrouhard** [comment]
Ping @maxbrunsfeld

**Comment by jdrouhard** [comment]
Ping @maxbrunsfeld

**Comment by jdrouhard** [comment]
Ping @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
This looks good, it just needs master merged into it.

@jdrouhard @calixteman Would either of you be interested in having write access to this repository and `tree-sitter-c`? You've done some great work on these repos. I think that ideally, you'd still submit PRs and get reviews from me and other maintainers for complex changes, but for more straightforward changes you could merge the PRs yourself. Let me know if you're open to that and I can send invites.

**Review by maxbrunsfeld — APPROVED** [review]

**Comment by jdrouhard** [comment]
That works for me! 👍

**Comment by calixteman** [comment]
WFM too.

**Comment by maxbrunsfeld** [comment]
Ok, invites sent. Feel free to email me if you have questions. For PRs like this that don't expand the parser dramatically, you both should feel free to merge them yourselves.  Thanks!

**Comment by jdrouhard** [comment]
@calixteman did you want to rebase your branch, regenerate, and merge this?

**Pull request merged**
