### PR TITLE
Add c++ attributes on statements

### PR DESCRIPTION
**Pull request by calixteman**
For reference:
https://en.cppreference.com/w/cpp/language/statements

### CODE REVIEW

**Comment by calixteman** [comment]
@maxbrunsfeld, ping ?

**Comment by theHamsta** [comment]
@maxbrunsfeld I guess this could be really useful. Attributes cause right now a lot of parser errors.

A rebase requires however a `tree-sitter generate`.

**Comment by calixteman** [comment]
I regenerated the parser using tree-sitter 0.19.1 since I think there is something wrong with 0.19.4 (or wrong in this grammar):
https://github.com/tree-sitter/tree-sitter/issues/1016

**Comment by XVilka** [comment]
Please rebase to solve the conflicts, especially since https://github.com/tree-sitter/tree-sitter-cpp/commit/c61212414a3e95b5f7507f98e83de1d638044adc fix for the grammar.

**Review by jdrouhard — APPROVED** [review]
This LGTM.

**Pull request merged**
