### PR TITLE
Add "this" keyword

### PR DESCRIPTION
**Pull request by vladh**

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by ahlinc** [comment]
@aryx Could you tell why this was merged with failed tests?

https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter-cpp/builds/46991606
```
Error in query file "highlights.scm"
Caused by:
    Query error at 63:3. Invalid node type this
```
_This also broke CI in the main repo what is not good:_ https://github.com/tree-sitter/tree-sitter/actions/runs/4961017184/jobs/8877280572#step:17:145

**Comment by vladh** [comment]
@ahlinc Sorry about this, not sure what the solution is is because surely “this” is just a string? I can't find anything [on this page](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) about "this" being reserved. Let me know what you'd like me to do.

**Comment by ahlinc** [comment]
Screenshot from 2023-05-13 10-38-29

The `this` is not a _string_ (anonymous terminal node) it's a real _named_ non terminal leaf node and it needs to be matched by the `(this)` rule.

**Comment by aryx** [comment]
@ahlinc I think when the PR was made, CI looked fine. Github has been down quite a few times lately, so maybe it coincided with one of those events.

**Comment by aryx** [comment]
In fact look: https://github.com/tree-sitter/tree-sitter-cpp/pull/202/checks there's nothing

**Comment by andrewtbiehl** [comment]
Hi. Just out of curiosity, since this change appears to introduce issues to this project, is this something that you plan to patch or roll back?

**Pull request merged**
